### ISSUE TITLE
about the error

### ISSUE THREAD

**Issue by spydr1** [sarisabban/RosettaDeNovo#1]
success 216
[+] Designing the structure
Exception ignored in: <bound method RosettaDesign.__del__ of <__main__.RosettaDesign object at 0x7f60746c79e8>>
Traceback (most recent call last):
  File "RamaNet.py", line 1163, in __del__
    os.remove('.resfile')
FileNotFoundError: [Errno 2] No such file or directory: '.resfile'
Traceback (most recent call last):
  File "RamaNet.py", line 1787, in <module>
    if __name__ == '__main__': main()
  File "RamaNet.py", line 1774, in main
    RD = RosettaDesign()
TypeError: __init__() missing 1 required positional argument: 'filename'

how can i treat this error ? 

thanks

**Comment by spydr1** [comment]
when i use the your guide code (python3 RamaNet.py --fragments USERNAME)
error is arose 
python3 RamaNet.py --f 'spydr'
RamaNet.py: error: unrecognized arguments: spydr

i think in your code, not include the USERNAME argument. 
so, when i use the "python3 RamaNet.py --f" 
an error has occurred.  (i was mentioned previous thing)

**Comment by sarisabban** [comment]
Apologies for the late reply. I did not get a notification of your issue.

Have you resolved the problem?  you must have a username from the Robetta server in order for this command to work
